### ISSUE TITLE
Issue while executing kobuki bump-and-go

### ISSUE THREAD

**Issue by jiban-jyoti** [JdeRobot/VisualStates-examples#23]
I am getting import error while executing kobuki bump-and-go.
Infrastructure : ROS melodic, ubuntu 18.04, Gazebo9
![Screenshot from 2020-01-19 23-44-30](https://user-images.githubusercontent.com/44982306/72676669-ebf0a980-3ab9-11ea-9f13-20f78660f328.png)

**Comment by okanasik** [comment]
Hello @jiban-jyoti, this problem seems to be related to the visualstates installation. Can you try the solution mentioned here: https://github.com/JdeRobot/VisualStates/issues/146#issuecomment-578314737

**Comment by jiban-jyoti** [comment]
![Screenshot from 2020-01-29 03-59-08](https://user-images.githubusercontent.com/44982306/73382584-c8b1cf80-42ed-11ea-9d2d-bff972a9a6a2.png)
Hello @okanasik I have tried using the new release of visualstates but there is a import error shown in the above image. Can you tell me how to configure the visualstates config as it is different from previous release.
![Screenshot from 2020-01-29 02-49-00](https://user-images.githubusercontent.com/44982306/73382730-19c1c380-42ee-11ea-8aac-ee066df7e2b9.png)

**Comment by okanasik** [comment]
Dear @jiban-jyoti, can you try to run the behavior as ROS package. If you check the readme file of the example (https://github.com/JdeRobot/VisualStates-examples/tree/master/kobuki_bump_and_go), you are supposed to have catkin workspace such that you can run the behavior using the following command
```rosrun kobuki_bump_and_go kobuki_bump_and_go.py --displaygui=true```

**Comment by jiban-jyoti** [comment]
Hello sir, I am working on the Catkin_ws and the python file generated is saved in generated files folder. After running catkin_make. I run the command

rosrun kobuki_bump_and_go kobuki_bump_and_go.py --displaygui=true

It is showing the following error.
![Screenshot from 2020-01-30 23-49-43](https://user-images.githubusercontent.com/44982306/73451390-84760c00-438d-11ea-908b-2465629dae85.png)

**Comment by okanasik** [comment]
Can you check that when you do `catkin_make` `kobuki_bump_and_go` should be listed as processed project. If it is listed and you still get the same error, source the devel/setup.bash of your workspace workspace with the command `source <path to workspace>/devel/setup.bash`

**Comment by jiban-jyoti** [comment]
I am confused regarding where to save the generated python file and should I give kobuki_bump_go as the name of folder to store the generated python file in catkin_ws or I am doing wrong.
![Screenshot from 2020-02-04 01-59-48](https://user-images.githubusercontent.com/44982306/73663900-76ddc080-46c4-11ea-922d-63feab43a6be.png)

**Comment by jiban-jyoti** [comment]
![Screenshot from 2020-02-04 02-33-13](https://user-images.githubusercontent.com/44982306/73667134-d38faa00-46c9-11ea-9578-ee2e2c1dcb24.png)
![Screenshot from 2020-02-04 02-32-58](https://user-images.githubusercontent.com/44982306/73667159-dbe7e500-46c9-11ea-91f8-47170863162f.png)
![Screenshot from 2020-02-04 02-32-47](https://user-images.githubusercontent.com/44982306/73667222-f752f000-46c9-11ea-97cc-faee76d7cc8d.png)
1. First Screenshot shows the visualStates output.
2. Second Screenshot shows the catkin_ws/src
3. Third Screenshot shows the  error while running the rosrun kobuki_bump_and_go kobuki_bump_and_go.py --displaygui=true

**Comment by okanasik** [comment]
Dear @jiban-jyoti, to generate a behavior:
- you first create a directory in `<catkin_ws>/src` catkin workspace. 
- Copy the behavior xml file from visualstates-examples folder to this newly created directory. 
- Then navigate to the behavior directory in the command line. 
- While you are in this directory, run visualstates and generate python code by running `rosrun visualstates main.py kobuki_bump_and_go.xml` 
- In GUI generate python code and close the visualstates.
- run `catkin_make` in the catkin workspace directory and make sure that generated kobuki_bump_and_go.py is executable. 
- You can make it executable by running `chmod +x kobuki_bump_and_go.py` in the directory of the behavior.
- Finally you should be able to run the behavior with `rosrun kobuki_bump_and_go kobuki_bump_and_go.py --displaygui=true`

**Comment by jiban-jyoti** [comment]
![Screenshot from 2020-02-05 22-34-45](https://user-images.githubusercontent.com/44982306/73838413-a104bf00-4839-11ea-9ef6-d54ce97dff61.png)
The instructions above worked for me thanks a lot. At the last step I was getting an attribute error shown in the screenshot.

**Comment by okanasik** [comment]
We know that error and we thought we already solve it. Can you create an issue with a full description and steps to reproduce the error?

**Comment by jiban-jyoti** [comment]
Sure sir. I am creating an issue now related to this. Otherwise, all the instructions are executing without any error.

**Comment by jiban-jyoti** [comment]
Also for the bump and go exercise in Robotics Academy Can I use the same instructions I have followed in VisualStates.
