### ISSUE TITLE
issue regarding behaviour files for kobuki bump and go and obstacle avoidance exercise

### ISSUE THREAD

**Issue by jiban-jyoti** [JdeRobot/VisualStates-examples#25]
![Screenshot from 2020-03-29 11-49-26](https://user-images.githubusercontent.com/44982306/77846591-b9a7aa80-71d4-11ea-894b-7974f20bae9e.png)
![Screenshot from 2020-03-29 15-48-38](https://user-images.githubusercontent.com/44982306/77846601-caf0b700-71d4-11ea-9483-44c8059fb0b4.png)
I was trying to execute bump and go exercise. First, I was facing error mentioning Global namespace instance has no attribute and then I make some changes with Behaviour xml file. After that everything seems perfect but bot is not moving.

I thought to try with Obstacle avoidance and faced an error AttributeError: **Namespace0 instance has no attribute 'calculate_obstacle'**

Maybe XML Files are outdated so we can update them to run these to exercises. @okanasik @pushkalkatara

**Comment by jiban-jyoti** [comment]
Steps to produce the error:

  

-   first create a directory in <catkin_ws>/src catkin workspace.
-   Copy the behavior xml file from visualstates-examples folder to this newly created directory.
-   Then navigate to the behavior directory in the command line.
-   While you are in this directory, run visualstates and generate python code by running rosrun    visualstates main.py kobuki_bump_and_go.xml
-   In GUI generate python code and close the visualstates.
-   run catkin_make in the catkin workspace directory and make sure that generated kobuki_bump_and_go.py is executable.
-   make it executable by running chmod +x kobuki_bump_and_go.py in the directory of the behavior.
-   Finally you should be able to run the behavior with rosrun kobuki_bump_and_go kobuki_bump_and_go.py --displaygui=true
After this step the error will pop up.

**Comment by pushkalkatara** [comment]
Hi @jiban-jyoti . yes maybe the xml files for obstacle avoidance were created with older version of VisualStates. It would be nice if you can recreate the example with latest version of VisualStates. 

Else, you can try with prius examples (https://jderobot.github.io/VisualStates/examples/prius_in_the_city) We'll update the Obstacle avoidance based examples soon.

**Comment by jiban-jyoti** [comment]
Hello @pushkalkatara. I will definitely check the prius examples. 
Also, I want to recreate the examples based on kobuki. Can you give me certain points or suggestion so that I can start working on it.

**Comment by pushkalkatara** [comment]
Yes sure!

There is detailed description about Global and Local namespace usage in VisualState here - https://jderobot.github.io/VisualStates/features/namespace

ObstacleAvoidance example is certainly simple, it uses a simple idea that if the laser sensor's value is less than a threshold, the robot has to rotate and avoid the obstacle.

Implementation details:
1. Use turtlebot with laser enabled, make a subscriber using VisualStates to read the laser data.
2. Create two states "Go" and "Turn" and connect them with a transition.
3. Create a function [calculate_obstacle](https://github.com/JdeRobot/VisualStates-examples/blob/2201dd6f3382e118f4cc60367d961a2596585e88/kobuki_obstacle_avoidance/kobuki_obstacle_avoidance.xml#L4) (refer here) and use in the tranisition condition.
4. Publish twist command in each state, in the Go state, publish twist with linear velocity component. in the Turn state, publish twist with angular velocity component.

Let me know if you face any issues.

**Comment by pankhurivanjani** [comment]
Solved for kobuki obstacle avoidance in #27
