### ISSUE TITLE
Error while running prius examples for ros-melodic

### ISSUE THREAD

**Issue by pankhurivanjani** [JdeRobot/VisualStates-examples#26]
The prius repo we are using
[prius_gazebo](https://github.com/pushkalkatara/prius_gazebo) or [car_demo](https://github.com/osrf/car_demo) support kinetic version.

While building the package there are errors due to this,
Attaching 2 lines from error logs:
```
/usr/include/ignition/msgs1/ignition/msgs/log_control.pb.h:346:92: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return base_path_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

```

What do you suggest for Prius case @jmplaza @pushkalkatara @okanasik ?

**Comment by jmplaza** [comment]
Hi @pankhurivanjani, 

I would suggest to use a car already stored in current LTS official ROS packages (ROS Melodic now and soon ROS Noetic) or in JdeRobot-base. 

(a) For instance there are several working cars already being used in some Academy exercises as in the [Global Navigation exercise](https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/global_navigation/) . This one lacks of images as far as I remember.

(b) There is another working car in the [Car junction exercise](https://jderobot.github.io/RoboticsAcademy/portfolio/car-junction/l). It includes 3 cameras. 

(c) Maybe we can integrate the modified prius car in @pushkalkatara 's repo into JdeRobot-base (plugins) and JdeRobot-assets (models, textures...) and then keep it maintained and working with LTS ROS distributions. But this would take developing time (BTW what do you think of it @pushkalkatara ?)

I suggest to follow (b), it is the fastest way to have the VisualStates-examples working again and requiring no more than updating the configuration files (launch...). In VisualStates-examples the focus is VisualStates itself so we could downgrade to a uglier but working family car. The "installation" of the car should not be required at all, it should just be included in general packages.

Talk to @SakshayMahna as he is updating the Car Junction exercise at JdeRobot Academy and has it working fine.

**Comment by SakshayMahna** [comment]
The Car Junction exercise uses [OpelROS](https://github.com/JdeRobot/assets/tree/master/jderobot_assets/models/opel_ROS) model present in the assets folder. It runs without any errors and uses the mentioned ROS topics to send images.

**Comment by pushkalkatara** [comment]
Hi all,

I think (b) would be the best strategy to add melodic support in VisualStates.

**Comment by pankhurivanjani** [comment]
Let's go with (b), I will see what all changes are required now.

**Comment by pankhurivanjani** [comment]
Currently due to issues with prius drivers in ROS Melodic we are using other robots like roomba hence closing this issue.
