### ISSUE TITLE
Prius plugins not supported with Gazebo 9.

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates-examples#7]
Publishing throttle, brake, steer on /prius topic doesn't move the vehicle in Gazebo 9, but works in Gazebo 8.

**Comment by okanasik** [comment]
Dear @pushkalkatara, can you check that prius plugins are compiled and properly loaded by the simulator? I am able to run your examples with Gazebo 9.

**Comment by pushkalkatara** [comment]
Solved in the recent commit in pull request - https://github.com/JdeRobot/VisualStates-examples/pull/5
